# Create an array


You can use the NumPy package to create arrays. NumPy arrays are optimized for numerical analyses and contain only a single data type. To convert a list to an array, you can use the `array()` function from NumPy.


In [1]:
# Import numpy as np
import numpy as np

# Lists
prices = [170.12, 93.29, 55.28, 145.30, 171.81, 59.50, 100.50]
earnings = [9.2, 5.31, 2.41, 5.91, 15.42, 2.51, 6.79]

# NumPy arrays
prices_array = np.array(prices)
earnings_array = np.array(earnings)

# Print the arrays
print(prices_array)
print(earnings_array)

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]


# Elementwise operations on arrays


Arrays allow for efficient numerical manipulation of its elements. Let's explore element-wise mathematical operations by calculating price to earnings ratio using two arrays, prices_array and earnings_array from the previous exercise.

This price to earnings ratio, or PE ratio, is a financial indicator of the dollar amount an investor can expect to invest in a company in order to receive one dollar of that company’s earnings.


In [2]:
# Import numpy as np
import numpy as np

# Create PE ratio array
pe_array = prices_array / earnings_array

# Print pe_array
print(pe_array)

[18.49130435 17.56873823 22.93775934 24.58544839 11.14202335 23.70517928
 14.8011782 ]


# Subsetting elements from an array


Subsetting arrays is similar to subsetting lists.


In [3]:
# Subset the first three elements
prices_subset_1 = prices_array[:3]
print(prices_subset_1)

# Subset last three elements 
prices_subset_2 = prices_array[-3:]
print(prices_subset_2)

# Subset every third element
prices_subset_3 = prices_array[0:7:3]
print(prices_subset_3)

[170.12  93.29  55.28]
[171.81  59.5  100.5 ]
[170.12 145.3  100.5 ]


# Creating a 2D array


Multi-dimensional arrays can be useful for several tasks. In finance, for example, a 2D array may be used to store the prices and earnings for various companies. Let's create this 2D array, stock_array, from a list of prices and earnings.


In [4]:
# Create a 2D array of prices and earnings
stock_array = np.array([prices, earnings])
print(stock_array)

# Print the shape of stock_array
print(stock_array.shape)

# Print the size of stock_array
print(stock_array.size)

[[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
 [  9.2    5.31   2.41   5.91  15.42   2.51   6.79]]
(2, 7)
14


In [5]:
# Transpose stock_array
stock_array_transposed = np.transpose(stock_array)
print(stock_array_transposed)

# Print the shape of stock_array
print(stock_array_transposed.shape)

# Print the size of stock_array
print(stock_array_transposed.size)

[[170.12   9.2 ]
 [ 93.29   5.31]
 [ 55.28   2.41]
 [145.3    5.91]
 [171.81  15.42]
 [ 59.5    2.51]
 [100.5    6.79]]
(7, 2)
14


# Subsetting 2D arrays


Subsetting 2D arrays is similar to subsetting nested lists. In a 2D array, the indexing or slicing must be specific to the dimension of the array.


In [6]:
# Subset prices from stock_array_transposed
prices = stock_array_transposed[:, 0]
print(prices)

# Subset earnings from stock_array_transposed
earnings = stock_array_transposed[:,1]
print(earnings)

# Subset the price and earning for first company
company_1 = stock_array_transposed[0,:]
print(company_1)

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]
[170.12   9.2 ]


# Calculating array stats


Not only can you perform elementwise calculations on NumPy arrays, you can also calculate summary stats such as mean and standard deviation of arrays using functions from NumPy.


In [7]:
# Calculate the mean 
prices_mean = np.mean(prices)
print(prices_mean)

# Calculate the standard deviation 
prices_std = np.std(prices)
print(prices_std)

113.6857142857143
45.51277932221513


# Generating a sequence of numbers


You may want to create an array of a range of numbers (e.g., 1 to 10) without having to type in every single number. The NumPy function `arange()` is an efficient way to create numeric arrays of a range of numbers.


In [8]:
# Create and print company IDs
company_ids = np.arange(1, 8, 1)
print(company_ids)

# Use array slicing to select specific company IDs
company_ids_odd = np.arange(1, 8, 2)
print(company_ids_odd)

[1 2 3 4 5 6 7]
[1 3 5 7]


# Who's above average?


Boolean arrays can be a very powerful way to subset arrays. In this exercise, you will identify the prices that are greater than average from a list of prices.


In [9]:
# Find the mean
price_mean = np.mean(prices)

# Create boolean array
boolean_array = prices > price_mean
print(boolean_array)

# Select prices that are greater than average
above_avg = prices[boolean_array]
print(above_avg)

[ True False False  True  True False False]
[170.12 145.3  171.81]


# Who's in health care?


In this exercise, you are provided the names of companies with their associated sector, and your goal is to find all companies that are associated with health care sector.


In [10]:
sectors = np.array(['Information Technology', 'Health Care', 'Health Care',
       'Information Technologies', 'Health Care'], dtype='<U24')

names = np.array(['Apple Inc', 'Abbvie Inc', 'Abbott Laboratories',
       'Accenture Technologies', 'Allergan Plc'], dtype='<U22')

# Create boolean array
boolean_array = (sectors == 'Health Care')
print(boolean_array)

# Print only health care companies
health_care = names[boolean_array]
print(health_care)

[False  True  True False  True]
['Abbvie Inc' 'Abbott Laboratories' 'Allergan Plc']
